# CircleCI configuration file
#
# Referencing https://circleci.com/docs/2.0/language-clojure/

version: 2

#
# Individual job definitions
#

art-job: &art-job
  environment:
    LEIN_ROOT: "true"
    # Customize the JVM maximum heap limit
    JVM_OPTS: -Xmx3200m

  steps:
    - checkout
    - restore_cache:
        keys:
          - m2-deps-{{ checksum "ash-ra-template/project.clj" }}-{{ checksum "boot-art/boot.properties" }}-{{ checksum "boot-art/build.boot" }}
          # fallback to using the latest cache if no exact match is found
          - m2-deps-
    - run:
        command: lein build
        working_directory: ash-ra-template
    - run:
        command: boot test
        working_directory: boot-art
    - save_cache:
        key: m2-deps-{{ checksum "ash-ra-template/project.clj" }}-{{ checksum "boot-art/boot.properties" }}-{{ checksum "boot-art/build.boot" }}
        paths:
          - ~/.m2

jobs:
  ash-ra-template-jdk-8-job:
    <<: *art-job
    docker:
      - image: circleci/clojure:openjdk-8-lein-2.9.1
  boot-art-jdk-8-job:
    <<: *art-job
    docker:
      - image: circleci/clojure:openjdk-8-boot-2.8.2
  ash-ra-template-jdk-11-job:
    <<: *art-job
    docker:
      - image: circleci/clojure:openjdk-11-lein-2.9.1
  boot-art-jdk-11-job:
    <<: *art-job
    docker:
      - image: circleci/clojure:openjdk-11-boot-2.8.2

workflows:
  version: 2
  build-all:
    jobs:
      - ash-ra-template-jdk-8-job
      - boot-art-jdk-8-job:
          requires:
            - ash-ra-template-jdk-8-job
      - ash-ra-template-jdk-11-job
      - boot-art-jdk-11-job:
          requires:
            - ash-ra-template-jdk-11-job
