# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2

#
# Individual job definitions
#

ash-ra-template-job: &ash-ra-template-job
  environment:
    LEIN_ROOT: "true"
    # Customize the JVM maximum heap limit
    JVM_OPTS: -Xmx3200m

  steps:
    - checkout
    - restore_cache:
        keys:
          - ash-ra-template-{{ checksum "ash-ra-template/project.clj" }}
          # fallback to using the latest cache if no exact match is found
          - ash-ra-template-
    - run:
        command: lein deps
        working_directory: ash-ra-template
    - save_cache:
        key: ash-ra-template-{{ checksum "ash-ra-template/project.clj" }}
        paths:
          - ~/.m2
    - run:
        command: lein build
        working_directory: ash-ra-template
    - persist_to_workspace:
        root: .
        paths: .

boot-art-job: &boot-art-job
  steps:
    - attach_workspace:
        at: ./
    - restore_cache:
        keys:
          - boot-art-dependencies-{{ checksum "boot-art/boot.properties" }}-{{ checksum "boot-art/build.boot" }}
          # fallback to using the latest cache if no exact match is found
          - boot-art-dependencies-
    - run:
        command: pwd
#        working_directory: boot-art
    - run:
        command: ls -al
#        working_directory: boot-art
    - run:
        command: boot test
#        working_directory: boot-art
    - save_cache:
        key: boot-art-dependencies-{{ checksum "boot-art/boot.properties" }}-{{ checksum "boot-art/build.boot" }}
        paths:
          - ~/.boot/cache/bin
          - ~/.boot/cache/lib
          - ~/.m2

jobs:
  ash-ra-template-jdk-8-job:
    <<: *ash-ra-template-job
    docker:
      - image: circleci/clojure:openjdk-8-lein-2.9.1
  boot-art-jdk-8-job:
    <<: *boot-art-job
    docker:
      - image: circleci/clojure:openjdk-8-boot-2.8.2
  ash-ra-template-jdk-11-job:
    <<: *ash-ra-template-job
    docker:
      - image: circleci/clojure:openjdk-11-lein-2.9.1
  boot-art-jdk-11-job:
    <<: *boot-art-job
    docker:
      - image: circleci/clojure:openjdk-11-boot-2.8.2

workflows:
  version: 2
  build-all:
    jobs:
      - ash-ra-template-jdk-8-job
      - boot-art-jdk-8-job:
          requires:
            - ash-ra-template-jdk-8-job
      - ash-ra-template-jdk-11-job
      - boot-art-jdk-11-job:
          requires:
            - ash-ra-template-jdk-11-job
