# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2
jobs:
  build-ash-ra-template:
    docker:
      - image: circleci/clojure:openjdk-8-lein-2.9.1

    environment:
      LEIN_ROOT: "true"
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m

    working_directory: ./ash-ra-template

    steps:
      - checkout
      - restore_cache:
          keys:
            - ash-ra-template-{{ checksum "project.clj" }}
            # fallback to using the latest cache if no exact match is found
            - ash-ra-template-
      - run: lein deps
      - save_cache:
          key: ash-ra-template-{{ checksum "project.clj" }}
          paths:
            - ~/.m2
      - run: lein build

  build-boot-art:
    docker:
      - image: circleci/clojure:openjdk-8-boot-2.8.2

    working_directory: ./boot-art

    steps:
      - checkout
      - restore_cache:
          keys:
            - boot-art-dependencies-{{ checksum "boot.properties" }}-{{ checksum "build.boot" }}
            # fallback to using the latest cache if no exact match is found
            - boot-art-dependencies-
      - run: boot test
      - save_cache:
          key: boot-art-dependencies-{{ checksum "boot.properties" }}-{{ checksum "build.boot" }}
          paths:
            - ~/.boot/cache/bin
            - ~/.boot/cache/lib
            - ~/.m2
